"""Real analytics data access for the frontend."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pandas as pd
import streamlit as st

from src.analytics.insights import amenity_summary, locality_price_trends, property_type_summary
from src.config.paths import (
    DATA_DIR,
    DEFAULT_FEATURE_IMPORTANCE_PATH,
    DEFAULT_METRICS_PATH,
    DEFAULT_MODEL_METADATA_PATH,
    DEFAULT_RECOMMENDER_DATA,
    DEFAULT_TRAINING_DATA,
    MODEL_DIR,
)


@st.cache_data(show_spinner=False)
def load_market_data() -> pd.DataFrame:
    """Load the real processed modeling dataset."""

    return pd.read_csv(DEFAULT_TRAINING_DATA)


@st.cache_data(show_spinner=False)
def load_apartment_data() -> pd.DataFrame:
    """Load project metadata used by the recommender."""

    if not DEFAULT_RECOMMENDER_DATA.exists():
        return pd.DataFrame()
    return pd.read_csv(DEFAULT_RECOMMENDER_DATA)


@st.cache_data(show_spinner=False)
def load_geo_market_data() -> pd.DataFrame:
    """Load sector-level pricing data with parsed Gurgaon coordinates."""

    latlong_path = DATA_DIR / "external" / "latlong.csv"
    if not latlong_path.exists():
        return pd.DataFrame()

    market = load_market_data().copy()
    coords = pd.read_csv(latlong_path)
    coords[["lat", "lon"]] = coords["coordinates"].apply(_parse_coordinates).apply(pd.Series)
    grouped = (
        market.groupby("sector", dropna=False)
        .agg(
            median_price=("price", "median"),
            median_area=("built_up_area", "median"),
            listing_count=("price", "size"),
        )
        .reset_index()
    )
    grouped["price_per_sqft"] = (grouped["median_price"] * 10_000_000) / grouped["median_area"]
    merged = grouped.merge(coords[["sector", "lat", "lon"]], on="sector", how="inner")
    return merged.dropna(subset=["lat", "lon"])


@st.cache_data(show_spinner=False)
def load_locality_trends() -> pd.DataFrame:
    """Load sector-level market trends."""

    return locality_price_trends(load_market_data())


@st.cache_data(show_spinner=False)
def load_property_type_summary() -> pd.DataFrame:
    """Load property-type summary metrics."""

    return property_type_summary(load_market_data())


@st.cache_data(show_spinner=False)
def load_amenity_summary() -> pd.DataFrame:
    """Load amenity and furnishing summary metrics."""

    return amenity_summary(load_market_data())


@st.cache_data(show_spinner=False)
def load_model_metrics() -> dict[str, float]:
    """Load model metrics generated by training."""

    return _read_json(DEFAULT_METRICS_PATH)


@st.cache_data(show_spinner=False)
def load_model_metadata() -> dict[str, Any]:
    """Load model metadata generated by training."""

    return _read_json(DEFAULT_MODEL_METADATA_PATH)


@st.cache_data(show_spinner=False)
def load_feature_importance() -> pd.DataFrame:
    """Load saved feature importance table."""

    if not DEFAULT_FEATURE_IMPORTANCE_PATH.exists():
        return pd.DataFrame(columns=["feature", "importance"])
    return pd.read_csv(DEFAULT_FEATURE_IMPORTANCE_PATH)


def model_artifact_status() -> dict[str, Any]:
    """Return local model artifact status for operational visibility."""

    artifact = MODEL_DIR / "price_model.joblib"
    return {
        "exists": artifact.exists(),
        "path": str(artifact),
        "size_mb": round(artifact.stat().st_size / (1024 * 1024), 2) if artifact.exists() else 0.0,
    }


def recent_predictions() -> pd.DataFrame:
    """Return recent predictions captured during the current Streamlit session."""

    records = st.session_state.get("recent_predictions", [])
    return pd.DataFrame(records)


def append_recent_prediction(record: dict[str, Any]) -> None:
    """Store a recent prediction in session state."""

    records = list(st.session_state.get("recent_predictions", []))
    records.insert(0, record)
    st.session_state["recent_predictions"] = records[:10]


def _read_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def _parse_coordinates(value: object) -> tuple[float | None, float | None]:
    text = str(value)
    try:
        lat_part, lon_part = text.split(",")
        lat = float(lat_part.replace("° N", "").strip())
        lon = float(lon_part.replace("° E", "").strip())
        return lat, lon
    except (ValueError, AttributeError):
        return None, None
