"use client";

import Link from "next/link";
import { Bookmark, ChevronRight, Compass, Settings2 } from "lucide-react";
import { useEffect, useState } from "react";
import { api, ApiError } from "@/lib/api";
import type { Preferences, Property } from "@/lib/types";
import { RequireAuth, useAuth } from "@/components/auth-provider";
import { PropertyCard } from "@/components/property-card";
import { PageIntro, PublicShell, SkeletonCards } from "@/components/shell";

function DashboardContent() {
  const { user } = useAuth(); const [recommendations, setRecommendations] = useState<Property[]>([]); const [saved, setSaved] = useState<Property[]>([]); const [preferences, setPreferences] = useState<Preferences | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { void load(); }, []);
  async function load() { try { const [recommendationResponse, savedResponse, preferenceResponse] = await Promise.all([api.recommendations({ top_n: 6 }), api.favorites(), api.getPreferences()]); setRecommendations(recommendationResponse.recommendations); setSaved(savedResponse.properties); setPreferences(preferenceResponse); } catch (e) { setError(e instanceof ApiError ? e.message : "Could not load your dashboard."); } finally { setLoading(false); } }
  return <PublicShell><div className="container page-wrap"><div className="dashboard-banner"><div><div className="eyebrow">Your EstateIQ workspace</div><h1>Good to see you, {user?.full_name?.split(" ")[0] || "there"}.</h1><p>Your search, organized around the signals you care about.</p></div><Link className="button button-sage" href="/profile"><Settings2 size={15} /> Update preferences</Link></div>{error && <div className="error-banner dashboard-error">{error}</div>}<div className="section-heading dashboard-heading"><div><div className="eyebrow">Personalized discovery</div><h2>Recommended for you</h2><p>Ranked from your preferences, valuation advantage, trust and market signals.</p></div><Link className="text-link" href="/properties">Explore all <ChevronRight size={15} /></Link></div>{loading ? <SkeletonCards count={3} /> : recommendations.length ? <div className="property-grid">{recommendations.slice(0, 3).map((property) => <PropertyCard key={property.id} property={property} />)}</div> : <div className="empty-state"><div className="empty-icon"><Compass size={18} /></div><h3>Set your search preferences</h3><p>Tell EstateIQ your budget, localities and configuration to make this view more useful.</p><Link className="button button-sage" href="/profile">Set preferences</Link></div>}<div className="dashboard-grid dashboard-section"><section className="dashboard-panel"><div className="section-heading"><div><div className="eyebrow">Saved properties</div><h2>Your shortlist</h2></div><Link className="text-link" href="/saved">View all →</Link></div>{loading ? <SkeletonCards count={1} /> : saved.length ? <PropertyCard property={saved[0]} compact /> : <div className="mini-empty"><Bookmark size={18} /><span>Save a property to build your shortlist.</span></div>}</section><section className="dashboard-panel"><div className="eyebrow">Your brief</div><h2>Search preferences</h2><div className="preference-summary"><div><span>Budget</span><strong>{preferences?.budget_min || preferences?.budget_max ? `₹${preferences.budget_min || 0} – ₹${preferences.budget_max || "open"} Cr` : "Not set"}</strong></div><div><span>Configuration</span><strong>{preferences?.preferred_bhk?.length ? preferences.preferred_bhk.map((value) => `${value} BHK`).join(", ") : "Any BHK"}</strong></div><div><span>Localities</span><strong>{preferences?.preferred_localities?.length ? preferences.preferred_localities.join(", ") : "Gurgaon-wide"}</strong></div></div><Link className="button button-ghost" href="/profile">Edit preferences</Link></section></div></div></PublicShell>;
}

export default function DashboardPage() { return <RequireAuth><DashboardContent /></RequireAuth>; }
